// Pont sécurisé renderer <-> main (contextIsolation activé).
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  configStatus: () => ipcRenderer.invoke('config-status'),
  appVersion: () => ipcRenderer.invoke('app-version'),
  updateCheck: () => ipcRenderer.invoke('update-check'),
  updateApply: () => ipcRenderer.invoke('update-apply'),

  whoami: () => ipcRenderer.invoke('whoami'),
  login: () => ipcRenderer.invoke('login'),
  tokenSet: (token) => ipcRenderer.invoke('token-set', token),
  tokenClear: () => ipcRenderer.invoke('token-clear'),

  // Multi-comptes
  accountsList: () => ipcRenderer.invoke('accounts-list'),
  accountSave: (label) => ipcRenderer.invoke('account-save', label),
  accountRemove: (id) => ipcRenderer.invoke('account-remove', id),
  accountActivate: (id) => ipcRenderer.invoke('account-activate', id),

  check: (name) => ipcRenderer.invoke('check', name),
  changeUsername: (name) => ipcRenderer.invoke('change-username', name),
  nameChangeInfo: () => ipcRenderer.invoke('namechange-info'),
  ntp: () => ipcRenderer.invoke('ntp'),

  generate: (opts) => ipcRenderer.invoke('generate', opts),
  variants: (base) => ipcRenderer.invoke('variants', base),
  clipboardWrite: (text) => ipcRenderer.invoke('clipboard-write', text),
  prefsGet: () => ipcRenderer.invoke('prefs-get'),
  prefsSet: (obj) => ipcRenderer.invoke('prefs-set', obj),
  rankNames: (names) => ipcRenderer.invoke('rank-names', names),
  historyStats: () => ipcRenderer.invoke('history-stats'),
  historyLookup: (name) => ipcRenderer.invoke('history-lookup', name),
  historySearch: (q) => ipcRenderer.invoke('history-search', q),
  historyFreeAll: () => ipcRenderer.invoke('history-free-all'),
  historyClear: () => ipcRenderer.invoke('history-clear'),
  checkpointSave: (data) => ipcRenderer.invoke('checkpoint-save', data),
  checkpointSaveRaw: (str) => ipcRenderer.invoke('checkpoint-save-raw', str),
  checkpointLoad: () => ipcRenderer.invoke('checkpoint-load'),
  checkpointClear: () => ipcRenderer.invoke('checkpoint-clear'),

  watchGet: () => ipcRenderer.invoke('watch-get'),
  watchAdd: (names) => ipcRenderer.invoke('watch-add', names),
  watchRemove: (name) => ipcRenderer.invoke('watch-remove', name),
  watchClear: () => ipcRenderer.invoke('watch-clear'),
  monitorStart: () => ipcRenderer.invoke('monitor-start'),
  monitorStop: () => ipcRenderer.invoke('monitor-stop'),
  monitorStatus: () => ipcRenderer.invoke('monitor-status'),
  monitorAutoclaim: (v) => ipcRenderer.invoke('monitor-autoclaim', v),
  webhookGet: () => ipcRenderer.invoke('webhook-get'),
  webhookSet: (p) => ipcRenderer.invoke('webhook-set', p),
  webhookTest: (url) => ipcRenderer.invoke('webhook-test', url),
  configExport: (payload) => ipcRenderer.invoke('config-export', payload),
  configImport: () => ipcRenderer.invoke('config-import'),
  pickTxt: () => ipcRenderer.invoke('pick-txt'),
  saveTxt: (payload) => ipcRenderer.invoke('save-txt', payload),
  bulkCheck: (payload) => ipcRenderer.invoke('bulk-check', payload),
  bulkStop: () => ipcRenderer.invoke('bulk-stop'),
  fetchProxies: () => ipcRenderer.invoke('fetch-proxies'),
  testProxies: (lines) => ipcRenderer.invoke('test-proxies', lines),

  snipe: (opts) => ipcRenderer.invoke('snipe', opts),
  stop: () => ipcRenderer.invoke('stop'),

  onLog: (cb) => ipcRenderer.on('log', (_e, data) => cb(data)),
  onDeviceCode: (cb) => ipcRenderer.on('device-code', (_e, data) => cb(data)),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_e, data) => cb(data)),
  onUpdateProgress: (cb) => ipcRenderer.on('update-progress', (_e, data) => cb(data)),
  onBulkResult: (cb) => ipcRenderer.on('bulk-result', (_e, data) => cb(data)),
  onBulkStats: (cb) => ipcRenderer.on('bulk-stats', (_e, data) => cb(data)),
  onProxyTestProgress: (cb) => ipcRenderer.on('proxy-test-progress', (_e, data) => cb(data)),
  onWatchFree: (cb) => ipcRenderer.on('watch-free', (_e, data) => cb(data)),
  onMonitorStatus: (cb) => ipcRenderer.on('monitor-status', (_e, data) => cb(data)),
});
